name = "Raccat 2026"
author = "Peppamy (initial pack), verbina29 (packwiz porting)"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "32fdf8a38bb8b0698d6a20b597f4aaf6d28ba11489e388f81a0214c4daa8c247"

[versions]
fabric = "0.19.3"
minecraft = "1.21.1"
unsup = "1.1.6"
