name = "Raccat 2026"
author = "Peppamy (initial pack), verbina29 (packwiz porting)"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5068107a3abe6becd584a1f0787b572f5b6b80e73f090479da01b8448d46344f"

[versions]
fabric = "0.19.3"
minecraft = "1.21.1"
unsup = "1.1.6"
