name = "Raccat 2026"
author = "Peppamy (initial pack), verbina29 (packwiz porting)"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6024ce6ae1198fe40754726c1c6740464c1e51a998501f2ed37b9f93d508af3b"

[versions]
fabric = "0.19.3"
minecraft = "1.21.1"
unsup = "1.1.6"
