[flavor_groups.particles]
name = "Particle Effects"
description = "Enable mods that add more particle effects."
side = "client"
choices = ["particles_on", "particles_off"]

[metafile.particle-effects]
flavors = ["particles_on"]
[metafile.make_bubbles_pop]
flavors = ["particles_on"]

[flavor_groups.shaders]
name = "Shaders"
description = "Install Iris, a mod that allows the use of shader packs."
side = "client"
choices = ["shaders_on", "shaders_off"]

[metafile.iris]
flavors = ["shaders_on"]
[metafile.sodium]
flavors = ["shaders_on"]

[flavor_groups.healthbars]
name = "Health Bars"
description = "Install a mod that adds health bars above entities."
side = "client"
choices = ["healthbars_on", "healthbars_off"]

[metafile.provis-health-bars]
flavors = ["healthbars_on"]

[flavor_groups.mousetweaks]
name = "Mouse Tweaks"
description = "Add Mouse Tweaks, a mod that adds some useful inventory management things like scrolling items."
side = "client"
choices = ["mousetweaks_on", "mousetweaks_off"]

[metafile.mouse-tweaks]
flavors = ["mousetweaks_on"]

[flavor_groups.controlling]
name = "Controlling"
description = "Adds the mod that lets you filter and search keybindings."
side = "client"
choices = ["controlling_on", "controlling_off"]

[metafile.controlling]
flavors = ["controlling_on"]
[metafile.searchables]
flavors = ["controlling_on"]

[flavor_groups.lootbeams]
name = "Loot Beams"
description = "Adds a mod that adds small beams above rare items."
side = "client"
choices = ["lootbeams_on", "lootbeams_off"]

[metafile.loot-beams-up]
flavors = ["lootbeams_on"]

[flavor_groups.utility]
name = "Utility"
description = "Adds some basic utility mods like Jade, AppleSkin, and Held Item Info. Jade tells you what block you're looking at, and AppleSkin tells you how much saturation and hunger food gives."
side = "client"
choices = ["utility_on", "utility_off"]

[metafile.jade]
flavors = ["utility_on"]
[metafile.held-item-info]
flavors = ["utility_on"]
[metafile.appleskin]
flavors = ["utility_on"]
